services:
  backend:
    build:
      context: ./Backend
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./Backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
    command: sh -c "npm install --prefer-offline && npm run dev"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./Frontend
    container_name: frontend
    ports:
      - "4200:4200"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NG_APP_API_URL=${NG_APP_API_URL}
    command: sh -c "npm install --prefer-offline && npm start -- --host 0.0.0.0"

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./Backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
